title: "Tomasz Gebarowski"
author: "Tomasz Gebarowski"
description: ""

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 5                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Theme settings
show_excerpts: true          # show article previews on the home page instead of headlines
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
dark_theme: false            # enables dark mode
dark_header: false           # uses dark header whether dark_theme is enabled or not
minimal_theme: false         # radically minimalistic theme

navigation:                  # show navigation links in the header
  - index.html
  - archive.md
  - about.md
  - publications.md
  - talks.md

#icons:                       # show icons in the header, for all possible icons see http://fontawesome.io/icons/
github: "https://github.com/tgebarowski"
twitter: "https://twitter.com/tgebarowski"
linkedin: "https://www.linkedin.com/in/tomaszgebarowski/"
stackoverflow: "https://stackoverflow.com/users/2455652/tgebarowski"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-131281312-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking


plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
 - jekyll-analytics
